ALTER TABLE t2
  ADD image VARCHAR(32) DEFAULT '';

ALTER TABLE t2
  ADD job CHAR(16) DEFAULT ' ';
  
ALTER TABLE t2
  DROP num ;
  
ALTER TABLE t2
  ADD job3 CHAR(16) ;
 
DESC t2

ALTER TABLE t2
  MODIFY job VARCHAR(20) ;
  
RENAME TABLE t2 TO table2;

ALTER TABLE table2 CHARACTER SET gbk;

ALTER TABLE table2 CHANGE job `name` VARCHAR(64);

DROP TABLE t1;